package com.mit.learning_english.shared

object UiErrorKey {
    const val UNKNOWN = "error_unknown"
    const val INVALID_SESSION = "error_invalid_session"
    const val LOGIN_FAILED = "error_login_failed"
    const val SIGNUP_FAILED = "error_signup_failed"
    const val UPLOAD_FAILED = "error_upload_failed"
    const val FAILED_LOAD_PAGES = "error_failed_load_pages"
    const val FAILED_LOAD_BOOKS = "error_failed_load_books"
    const val FAILED_SEARCH_BOOKS = "error_failed_search_books"
    const val FAILED_LOAD_AUTHORS = "error_failed_load_authors"
    const val FAILED_LOAD_BOOK_DETAIL = "error_failed_load_book_detail"
    const val CANNOT_READ_IMAGE = "error_cannot_read_image"
    const val CANNOT_GET_RESULTS = "error_cannot_get_results"
    const val UPDATE_PROGRESS_FAILED = "error_update_progress_failed"
    const val HTTP_ERROR = "error_http_error"
    const val DICTIONARY_CONNECTION = "error_dictionary_connection"
    const val ERROR_UPLOADING_FILE = "error_uploading_file"
    const val OTP_OR_EMAIL_MISSING = "error_otp_or_email_missing"
    const val PASSWORD_MISMATCH_OR_EMPTY = "error_password_mismatch_or_empty"
    const val EMAIL_REQUIRED = "error_email_required"
    const val COULD_NOT_LOAD_PROFILE = "error_could_not_load_profile"
    const val COULD_NOT_LOAD_STATS = "error_could_not_load_stats"
    const val LOAD_DATA_VI = "error_load_data_vi"
    const val CREATE_DECK_VI = "error_create_deck_vi"
    const val DELETE_FAILED = "error_delete_failed"
    const val REVIEW_FAILED = "error_review_failed"
    const val STUDY_COMPLETE_FAILED = "error_study_complete_failed"
    const val AUTH_SIGNUP_VI = "error_auth_signup_vi"
    const val FILL_TERM_DEFINITION = "error_please_fill_term_definition"
}
